### ISSUE TITLE
invalid regular expression

### ISSUE THREAD

**Issue by exomarty** [NicolasSiver/nodebb-plugin-ns-embed#1]
i failed on writing regular expresión and know it reload nodebb all time

29/11 22:41 [21315] - error: SyntaxError: Invalid regular expression: /?:https?:\/\/)?(?:twitter.com)\/([^\/"\s]_)\/statuse?s?\/([^\/"\s]_)(\/photo\/\d|)".*?>.+?<\/a>/g/: Nothing to repeat
    at new RegExp (<anonymous>)
    at /home/9node/NodeBB/node_modules/nodebb-plugin-ns-embed/plugin/rules.js:26:34
    at Array.map (native)
    at /home/9node/NodeBB/node_modules/nodebb-plugin-ns-embed/plugin/rules.js:24:31
    at /home/9node/NodeBB/node_modules/async/lib/async.js:52:16
    at /home/9node/NodeBB/node_modules/async/lib/async.js:1204:30
    at /home/9node/NodeBB/src/database/mongo/hash.js:53:4
    at handleCallback (/home/9node/Nod

**Comment by NicolasSiver** [comment]
I recommend to use this service to check if your regular expression "valid"

http://www.regexr.com/

**Comment by exomarty** [comment]
thank you but i cant reach the plugin to change it :dancer: 
uninstalling didnt work

**Comment by NicolasSiver** [comment]
You can delete rule that you have created for Twitter from the database.
It has key: `ns:embed:rule:x`, where `x` is id.
For example, if you have Mongo DB, you can use mongo shell, find for the document (Twitter Rule) and delete it.

**Comment by exomarty** [comment]
rule is ok but it lacks ( on the beggining
 i will try to delete it but i´m not expert on mongo Shell 
thanks

**Comment by NicolasSiver** [comment]
Enter mongo shell, `$ mongo`

```
use yourDbName //switch to your database
db.objects.find({_key: /ns:embed:rule:\d/}) //check if you can find anything
///when you will know id of the rule, delete it. For example, It's 5
db.objects.delete({_key:"ns:embed:rule:5"})
```

**Comment by NicolasSiver** [comment]
Or you could use with software - http://robomongo.org/
With it, it will be a bit simpler ;)
