### ISSUE TITLE
Incompatibility with NodeBB 1.10.2

### ISSUE THREAD

**Issue by Per0x** [NicolasSiver/nodebb-plugin-ns-embed#12]
After install and reboot, the plugin does not appear in the the latest version of NodeBB 1.10.2

**Comment by NicolasSiver** [comment]
NodeBB minor version changes are not about compatibility. There is a high chance that plugin is not compatible with 1.10.2

**Comment by FrankM64** [comment]
I like the plugin, but in v1.11.0 it don't work anymore. Do you plan to fix it?

**Comment by NicolasSiver** [comment]
Yes. Try a new v3 version. Let me know if issue was resolved. 

Regards

**Comment by Per0x** [comment]
It works well, thank you !!!

**Comment by FrankM64** [comment]
Problem solved. Thank you very much!
