### ISSUE TITLE
plugin disappeared in Admin Plugin list

### ISSUE THREAD

**Issue by navixco** [NicolasSiver/nodebb-plugin-ns-embed#15]
Hello,
Plugin worked fine with Nodebb 1.11 but after upgraded to Nodebb 1.12.0 embeded content appeared twice in website. Removed and reinstalled it, it appeared  in Installed and Active plugins but can not see it in Plugin list and ready to use.
Thanks for any advice!

![not-in-list-to-use](https://user-images.githubusercontent.com/46859025/54742244-73982e00-4bf3-11e9-87fc-ce7d14abac23.png)
![ns-embed Actived](https://user-images.githubusercontent.com/46859025/54742250-75fa8800-4bf3-11e9-8e6c-7c25eb9ce6c5.png)

**Comment by NicolasSiver** [comment]
Could it be related to the compatibility? Latest plugin version is compatible with NodeBB 1.11.0 only.

**Comment by navixco** [comment]
I changed to use iFrame and it will be easy to do.
Thanks @NicolasSiver
