### ISSUE TITLE
Not load js in embeded code

### ISSUE THREAD

**Issue by navixco** [NicolasSiver/nodebb-plugin-ns-embed#16]
Hello NicolasSiver,
Thanks for your embed plugin. I installed in my forum and working fine except the case there is javascript in embeded code.
I load js to calculate stream url to play video by videojs.
My Issue: 
Not load javascript in embeded code when open page at the first time, but it will be loaded if I refresh web page.
My Replace code:
`
<div class='embed-wrapper'><div class='embed-container'>
<div class="wrapper">
 <div class="vidpeocontent">
 <video-js id="video" class="vjs-default-skin" controls preload="auto" width="640" height="268"  poster='/assets/uploads/system/skillpy-poster.png'  data-setup='{}'>  
  </video-js>
  <script>
 var player = videojs('video');
player.fluid(true);
player.responsive(true);
      var stream = "$1";
var url = stream+"/index.m3u8";
   player.src({ 
      src: url, 
       type: 'application/x-mpegURL'
             });
  </script>
  </div></div>
</div></div>
`

.....
Thanks for any advice help me to load js with embeded code.
Navixco

**Comment by NicolasSiver** [comment]
Hello,

I do not see where is a video tag on top of which you try to create Video JS object.
Check this topic branch - https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/33 Maybe you could find an example of how to handle playback for the videos hosted on your website.

**Comment by navixco** [comment]
Thanks for your reply soon.
Noted that I need refresh page after open to see embeded content.
My forum used: Nodebb 1.12.0, videojs 7, Chrome Browser
I had refered to the link you recommended
https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/39

Link test:
https://www.skillpy.com/topic/36/test-1
Steps to get issus:
1.
https://www.skillpy.com/topic/36/test-1
-> OK
2.
Go Home
3.
click Back or click navigation: Test video -> Test 1
-> Embeded content not loaded. It will display when refresh page.

Here is my embeded code:
Watch:

`(?:<a.*?)?(?:https?:\/\/)?(?:media\.)?skillpy\.com\:4433\/hls\/([a-zA-Z0-9.+%_-]{4,100})(?:.*?\/a>)?`
Replace:

`
<div class="embed-wrapper"><div class="embed-container">
<div class="wrapper">
 <div class="videocontent">
 <video-js id="video" class="vjs-default-skin" controls preload="auto" width="640" height="268"  poster="/assets/uploads/system/skillpy-poster.png"  data-setup="{}">  
  </video-js>
  <script>
 var player = videojs("video");
player.responsive(true);
player.fluid(true);
      var stream = "$1";
      var str = stream+"/1_3/index.m3u8";
      var url = "https://media.skillpy.com:4433/hls/"+str;
   player.src({ 
      src: url, 
       type: "application/x-mpegURL"
             });
  </script>
  </div></div>
</div></div>
`

**Comment by navixco** [comment]
Thank @NicolasSiver. I changed to use iFrame and it will be simple and easy to do.
