### ISSUE TITLE
How to get current user id to change something in Replace code

### ISSUE THREAD

**Issue by navixco** [NicolasSiver/nodebb-plugin-ns-embed#17]
Hi,
I have an question need helping for my problem. 
I use this plugin to play video, and I need check that user logged in or not  to change something in Repace code. Example guests will be litmited watching time on each video.
I ever resolved it by using script in Replace code to check global variable app.user.uid is empty ot not. 
But I get another issue that:
1) this content of the script will be displayed on History of each post, so everyone can see this script code.
2) And when someone share post link to social network such as Facebook, the script code will be there.

So I find another solution to check current user status (logged or not) to change Rule in plugin.
Anyone can help me know how to get current user ID in this plugin? Ofcourse, Im still out door of Node.js and NodeBB.
Thanks for any suggestion.
Navix

**Comment by NicolasSiver** [comment]
Hello @navixco 

What you have described would be another plugin. This plugin is designed to replace recognizable code (rules). So if a user should not see a particular embed for video, something else should determine what current user (authenticated/guest) should see in terms of text and code. Where responsibility of this plugin just to augment post outputs.
