### ISSUE TITLE
YouTube profile links are attempted to be embedded

### ISSUE THREAD

**Issue by mstan** [NicolasSiver/nodebb-plugin-ns-embed#2]
If a YouTube profile link is provided in a post, the addon attempts to embed it and turns it into an invalid video.

**Comment by NicolasSiver** [comment]
Yes, It should not behave in such way.

**Comment by NicolasSiver** [comment]
@mstan Correct me If I'm wrong, Youtube provides only such URLs to Profiles `https://www.youtube.com/user/{ProfileName}`, doesn't it?

**Comment by mstan** [comment]
I believe so, yes.
