### ISSUE TITLE
what does $1, $2, etc means ?

### ISSUE THREAD

**Issue by kawhi66** [NicolasSiver/nodebb-plugin-ns-embed#23]
_Replacement, you can use capturing groups via $1, $2, etc._

I don't get it, what does this mean ?

**Comment by NicolasSiver** [comment]
If you plan to write your rule, it requires some Regular Expressions knowledge.
Here is some information about capturing groups - https://www.regular-expressions.info/brackets.html

**Comment by kawhi66** [comment]
> If you plan to write your rule, it requires some Regular Expressions knowledge.
> Here is some information about capturing groups - https://www.regular-expressions.info/brackets.html

@NicolasSiver  yeah, but I still have a question, this is my rule

Watch
```
(?:<a.*?)?(?:\/community\/assets\/uploads\/files\/(.+)\b\.mp4)(?:.*?\/a>)?
```

Replace
```
<div class='embed-wrapper'><div>$1</div><div class='embed-container'><iframe src='/community/assets/uploads/files/$1.mp4' frameborder='0' allowfullscreen></iframe></div></div>
```

something like `[design](/community/assets/uploads/files/design.mp4)` works fine, but `[design.mp4](/community/assets/uploads/files/design.mp4)` fails. **$1** will be `design.mp4">design`

why does this happen, the watch still has problem ?

**Comment by NicolasSiver** [comment]
Could you share HTML against which it fails? (Should include `<a>` tag, etc.)
You provided markdown, there are no issues with markdown you have provided.

**Comment by NicolasSiver** [comment]
I can make hypothesis, that this rule validating URL like this: `<a href="/community/assets/uploads/files/design.mp4">design.mp4</a>`
This part is greedy enough to capture everything from `/files/design.mp4` until `>design.mp4`, one of the possible solutions could be to prevent it from bu such greedy and change your capture group to `(.+?)`.

**Comment by kawhi66** [comment]
> I can make hypothesis, that this rule validating URL like this: `<a href="/community/assets/uploads/files/design.mp4">design.mp4</a>`
> This part is greedy enough to capture everything from `/files/design.mp4` until `>design.mp4`, one of the possible solutions could be to prevent it from bu such greedy and change your capture group to `(.+?)`.

@NicolasSiver `(.+?)` fix my problem, thank you sir.

**Comment by kawhi66** [comment]
Chinese new year is coming, happy new year !!!
