### ISSUE TITLE
twitter/facebook embed does not work

### ISSUE THREAD

**Issue by AliCihan** [NicolasSiver/nodebb-plugin-ns-embed#24]
somehow links disappeared but the plugin does not convert them to preview... Is this plugin compatible with 1.13.2?

**Comment by AliCihan** [comment]
the same issue with facebook and twitter links continue in NodeBB 1.13.3

**Comment by NicolasSiver** [comment]
Both integrations are very custom. Plugin ships with a few integrations that were designed to work with the plugin. I'm sure it's possible. The best place for help will be the forum thread here - https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/112 . Thank you.
