### ISSUE TITLE
How to use this plugin to embedded youtube and .mp4 files? 

### ISSUE THREAD

**Issue by salmanfarisvp** [NicolasSiver/nodebb-plugin-ns-embed#25]
I installed the plugin but didn't see any option related to this **nodebb-plugin-ns-embed plugin**.

**Comment by NicolasSiver** [comment]
Could you share your NodeBB version? Is it `1.13.x`?

**Comment by salmanfarisvp** [comment]
running on 1.12.2

**Comment by NicolasSiver** [comment]
As for Youtube, it's available by default. In admin, you have to click - Install Default Rules.
As for MP4, it's custom for everybody. Here is ane example from one of the users - https://community.nodebb.org/topic/7135/nodebb-plugin-ns-embed-ns-embed/95?_=1622475657795
