### ISSUE TITLE
Cannot Access Plugin Settings

### ISSUE THREAD

**Issue by nordskill** [NicolasSiver/nodebb-plugin-ns-embed#29]
Hi, after installing and activating the plugin I cannot access plugin settings. The embed links are not handled by the plugin. I assume that for the plugin to start work I have to press the "Install Default Rules" in the plugin settings.

## Steps taken:
1. install and activate the plugin via NodeBB admin panel
2. restart NodeBB via admin panel
3. check the URLs: *no embedded iframes*
4. check the "Plugins" dropdown menu in the admin panel: *no correspondent menu button*
5. stop NodeBB via Linux console
6. install the plugin manually via npm
7. start NodeBB
8. the same as points 3 & 4.

**NodeBB version: 1.16.0**

## Expectation:
Expected to see the plugin settings:

![NodeBB nodebb-plugin-ns-embed plugin settings](https://raw.githubusercontent.com/NicolasSiver/nodebb-plugin-ns-embed/master/screenshot.png)

**Comment by barisusakli** [comment]
You need to rebuild and restart after installing and activating the plugin.

**Comment by nordskill** [comment]
@barisusakli, that didn't help.
By the way, there is a "**nodebb-plugin-embed**" in npm. I don't know how it is related to the current one, but it has the same interface. And its settings page is visible in the Plugins menu. But the plugin [doesn't work properly](https://community.nodebb.org/topic/15204/nodebb-plugin-embed-ignores-iframe-attributes).

**Comment by NicolasSiver** [comment]
@nordskill plugin is not compatible with 1.16.
There is a major update to the plugin on the horizon. But you will need to upgrade to Nodebb v1.17 to use it.

**Comment by nordskill** [comment]
I tried the plugin with v1.17.0, but all the symptoms remained the same.

**Comment by nordskill** [comment]
Does plugins loading order influence anything?

**Comment by NicolasSiver** [comment]
No point to try the currently available plugin with 1.17. It will not work. Please wait for a new `v5` version of the plugin.
