### ISSUE TITLE
Support oEmbed

### ISSUE THREAD

**Issue by rintaun** [NicolasSiver/nodebb-plugin-ns-embed#3]
It would be really great to have support for [oEmbed](http://oembed.com/), which would allow for embedded tweets and more.

**Comment by NicolasSiver** [comment]
Looks interesting - http://oembed.com/providers.json

But It's a bit different implementation. Current embed logic is a synchronous operation, it's based on regular expression, and can have several use cases. For example for Youtube, it can parse several types of links.

With oEmbed plugin should create a HTTP request, which could be fast, but it will affect rendering speed. Very first optimization which could be made is a cache for oEmbed requests.

Twitter does not support oEmbed, I can't find them in the list of providers.
