### ISSUE TITLE
The following plugins may not be compatible with your version of NodeBB

### ISSUE THREAD

**Issue by loid345** [NicolasSiver/nodebb-plugin-ns-embed#34]
nodebb 1.19.1
nodebb-plugin-ns-embed 5.0
nodebb log: 2022-01-24T09:42:52.711Z [4567/10407] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
  * nodebb-plugin-ns-embed

**Comment by NicolasSiver** [comment]
Plugin ver. 6.0.0 was just released. It's compatible with the latest NodeBB 2.2.x
