### ISSUE TITLE
Can't use controlslist in video tag

### ISSUE THREAD

**Issue by Phxmark** [NicolasSiver/nodebb-plugin-ns-embed#36]
I write a rule to play video updated, but I don't want anybody to download it.
So I put controlslist="nodownload" in video tag:

`<video src="/assets/uploads/files/$1.mp4"  controls controlslist="nodownload" width="800px" height="500px">
</video>`

but it didn't work.
And I found the keyword controlslist didn't show up in web page element.

Is there any way to use controlslist or forbid users to download video?

**Comment by NicolasSiver** [comment]
If I remember correctly, content is sanitized with standard rules from NodeBB. So technically, NodeBB does not allow that property to get through.

**Comment by Phxmark** [comment]
> If I remember correctly, content is sanitized with standard rules from NodeBB. So technically, NodeBB does not allow that property to get through.

Thanks for your reply. 
I modify the filter rules of Nodebb, now it works.
