### ISSUE TITLE
Please, make it nodebb 2.0 compatible

### ISSUE THREAD

**Issue by NormandoHall** [NicolasSiver/nodebb-plugin-ns-embed#37]
Hello Nicolas. We love this plugin and it is very useful. Can you make it compatible to NodeBB 2.0? :pray:  :pray:  :pray: 

Thank you!

**Comment by NicolasSiver** [comment]
Plugin ver. 6.0.0 was just released. It's compatible with the latest NodeBB 2.2.x

**Comment by NormandoHall** [comment]
Thank you @NicolasSiver !
