### ISSUE TITLE
Add Twitch to default rules (rule inside)

### ISSUE THREAD

**Issue by am4nr** [NicolasSiver/nodebb-plugin-ns-embed#4]
Name: twitch
Display Name: Twitch
Watch: `(?:<a.*?)?(?:https?:\/\/)?(?:www\.)?twitch\.tv\/([a-zA-Z0-9_-]{4,11})(?:.*?\/a>)?`
Replace: `<div class='embed-wrapper'><div class='embed-container'><iframe src="http://player.twitch.tv/?channel=$1" allowfullscreen></iframe></div></div>`

**Comment by NicolasSiver** [comment]
Did they solve an issue with auto-play?
Actually, Twitch is in the Plugin Default Rules already, but It's disabled because of absent auto-play feature.

**Comment by jffz** [comment]
Just installed this rule and doesn't work on my nodebb, there is just an empty box

EDIT: Fixed, issue was related to SSL

**Comment by NicolasSiver** [comment]
I'm open to reactivate Twitch Rule, but only if Twitch provides an option to disable auto-play.
