### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by SiirRandall** [NicolasSiver/nodebb-plugin-ns-embed#6]
Is there a way to make a rule to take any URL that has jpg png gif etc to automatically show?

**Comment by NicolasSiver** [comment]
Yes, It's doable with this plugin. You can create rule which will look for Urls on images and replace it with `img` and necessary additional html elements.

**Comment by SiirRandall** [comment]
Awesome, I will play around with it. Nice work by the way.
