### ISSUE TITLE
Internally uploaded video embeddind as HTML5 player

### ISSUE THREAD

**Issue by l0co** [NicolasSiver/nodebb-plugin-ns-embed#7]
Would be nice to have default rules to embed videos uploaded to the posts. Here is example working with MP4:

Regex:

    <a href="/uploads/files/(.*).mp4">[^<]*</a>

Replacement:

    <video id="$1" src="/uploads/files/$1.mp4" controls style="width:800px"></video>
    <div><small><a href="/uploads/files/$1.mp4" target="_blank">Download video</a></small></div>

**Comment by NicolasSiver** [comment]
Is it something specific for every forum?

**Comment by l0co** [comment]
Yes. It works with every mp4 video uploaded to nodebb from markdown editor. It's easy to write one pattern to support more video formats.

**Comment by NicolasSiver** [comment]
Replacement rule does not use responsive layout provided with the plugin. It could be made in a more reusable fashion and added to Community Rules. Thanks.

**Comment by Marlin-Na** [comment]
I used the following rule and it works for me:

Regex:
```
<a href="/assets/uploads/files/(.*).mp4">[^<]*</a>
```

Replacement:
```
<div class='embed-wrapper'><div class='embed-container'>

<video src="/assets/uploads/files/$1.mp4" controls>
Your browser doesn't support HTML5 video.
Please <a href="/assets/uploads/files/$1.mp4">download</a> instead.
</video>

</div></div>
```

@NicolasSiver Please let me know if you want me to create a pull request to add it to community rules.

**Comment by kawhi66** [comment]
> I used the following rule and it works for me:
> 
> Regex:
> 
> ```
> <a href="/assets/uploads/files/(.*).mp4">[^<]*</a>
> ```
> 
> Replacement:
> 
> ```
> <div class='embed-wrapper'><div class='embed-container'>
> 
> <video src="/assets/uploads/files/$1.mp4" controls>
> Your browser doesn't support HTML5 video.
> Please <a href="/assets/uploads/files/$1.mp4">download</a> instead.
> </video>
> 
> </div></div>
> ```
> 
> @NicolasSiver Please let me know if you want me to create a pull request to add it to community rules.

what does $1 means, I don't get it

**Comment by kawhi66** [comment]
> I used the following rule and it works for me:
> 
> Regex:
> 
> ```
> <a href="/assets/uploads/files/(.*).mp4">[^<]*</a>
> ```
> 
> Replacement:
> 
> ```
> <div class='embed-wrapper'><div class='embed-container'>
> 
> <video src="/assets/uploads/files/$1.mp4" controls>
> Your browser doesn't support HTML5 video.
> Please <a href="/assets/uploads/files/$1.mp4">download</a> instead.
> </video>
> 
> </div></div>
> ```
> 
> @NicolasSiver Please let me know if you want me to create a pull request to add it to community rules.

what does $1 means, I don't get it

**Comment by kawhi66** [comment]
> I used the following rule and it works for me:
> 
> Regex:
> 
> ```
> <a href="/assets/uploads/files/(.*).mp4">[^<]*</a>
> ```
> 
> Replacement:
> 
> ```
> <div class='embed-wrapper'><div class='embed-container'>
> 
> <video src="/assets/uploads/files/$1.mp4" controls>
> Your browser doesn't support HTML5 video.
> Please <a href="/assets/uploads/files/$1.mp4">download</a> instead.
> </video>
> 
> </div></div>
> ```
> 
> @NicolasSiver Please let me know if you want me to create a pull request to add it to community rules.

what does $1 means, I don't get it

**Comment by kawhi66** [comment]
> I used the following rule and it works for me:
> 
> Regex:
> 
> ```
> <a href="/assets/uploads/files/(.*).mp4">[^<]*</a>
> ```
> 
> Replacement:
> 
> ```
> <div class='embed-wrapper'><div class='embed-container'>
> 
> <video src="/assets/uploads/files/$1.mp4" controls>
> Your browser doesn't support HTML5 video.
> Please <a href="/assets/uploads/files/$1.mp4">download</a> instead.
> </video>
> 
> </div></div>
> ```
> 
> @NicolasSiver Please let me know if you want me to create a pull request to add it to community rules.

what does $1 means, I don't get it
